include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    require_trailing_commas: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_print: true
    avoid_unused_constructor_parameters: true
    empty_constructor_bodies: true
    no_leading_underscores_for_local_identifiers: true
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unawaited_futures: true
    unnecessary_overrides: true
    unrelated_type_equality_checks: true
    use_key_in_widget_constructors: true